### ISSUE TITLE
Do you plan on releasing the source code?

### ISSUE THREAD

**Issue by RemiFabre** [captainl/training-arduino#5]
This seems to be a very nice work, but without the source code it's hard to contribute or even adapt to your own setup (e.g. wires soldered to differents GPIOs). Do you plan on releasing the source code?

**Comment by mbuciuman** [comment]
This guy has made it pretty clear he doesn't want to release source code. Feel free to check out my project if you want an open source training adapter.

**Comment by RemiFabre** [comment]
I just read your README and it seems to be an interesting work, thanks for sharing. I was thinking about coding the recording mode using a laptop connected to the micro controller to allow for features that are not possible on the embedded system.

Closing this issue.

**Comment by mbuciuman** [comment]
That sounds like an interesting approach to handling the recording. Also, feel free to send me an email if you have any questions or hit anything interesting.
